### ISSUE TITLE
Cohesion Link

### ISSUE THREAD

**Issue by krispy1298** [alexsomeoddpilot/Someoddpilot-Coding-Style#2]
take to FF media queries page

**Comment by alexsomeoddpilot** [comment]
Can you clarify where this is?

**Comment by krispy1298** [comment]
https://github.com/alexsomeoddpilot/Someoddpilot-Coding-Style/blob/master/principles.md#maximize-cohesion

**Comment by alexsomeoddpilot** [comment]
Fixed in 31b647b1a4920cbd90427b58f08bd3645324c3e6
