### ISSUE TITLE
subhead wrong?

### ISSUE THREAD

**Issue by krispy1298** [alexsomeoddpilot/Someoddpilot-Coding-Style#3]
https://github.com/alexsomeoddpilot/Someoddpilot-Coding-Style/blob/master/html.md#inline-attributes

shouldnt the second subhead for inline be "good"?

**Comment by alexsomeoddpilot** [comment]
Correct.

**Comment by alexsomeoddpilot** [comment]
Fixed in c0a90466455f91d4d9f8d0012d681d9ce41b325a
